name: pokemon_trainer_fitness_app
description: Una aplicación de consola para mantener un cuerpo saludable y obtener mejores Pokémon.
version: 1.0.0
# repository: https://github.com/chriskwork/poke_imc_console.git

environment:
    sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
    convert: ^3.1.2
    http: ^1.3.0
    mysql1: ^0.20.0
    # path: ^1.8.0

dev_dependencies:
    lints: ^5.0.0
    test: ^1.24.0
